name: pathvein
services:
  minio:
    command: server --console-address :9001 /data --address :9000
    container_name: pathvein-minio
    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
