name: pathvein
services:
  minio:
    command: server --console-address :19001 /data --address :19000
    container_name: pathvein-minio
    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin
    image: minio/minio:latest
    ports:
      - 19000:19000
      - 19001:19001
